---
title: "ostriches_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ostriches_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/ostrich_vignette-",
  out.width = "100%"
)
```

```{r setup}
library(blueostrich)
library(tidyverse)
library(leaflet)
```

## An amazing plot!

```{r gg}
ggplot(data = ostriches, aes(x = height_m, y = mass_kg)) +
  geom_point() +
  geom_text(aes(label = name), nudge_y = 1) +
  theme_light() +
  labs(x = "Height (m)",
       y = "Mass (kg)",
       title = "Ostrich size measurements")
```

```{r DT, echo = FALSE}
if (requireNamespace("htmltools", quietly = TRUE)) {
  htmlwidgets::setWidgetIdSeed(99)
}
DT::datatable(ostriches)
```

```{r}
library(leaflet)
  leaflet() %>%
  addTiles() %>%
  addMarkers(
  lng=174.768,
  lat=-36.852,
  popup="The birthplace of R"
)
```
